# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |cfg|

  cfg.vm.box = "centos/8"
  cfg.vm.hostname = "vm-n-1"
  cfg.vbguest.auto_update = false
 
  cfg.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "2"
  end
  
  cfg.ssh.insert_key = false
  cfg.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_ed25519']
  cfg.vm.provision :file, source: "~/.ssh/id_ed25519.pub", destination: "~/.ssh/authorized_keys"
  cfg.vm.provision :shell, path: "scripts/1_kernel_update.sh"
  
end
