# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :monitoring => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.150'
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "200"]
          end
          box.vm.provision "shell", inline: <<-EOL
            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
            sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            systemctl restart sshd
          EOL
          box.vm.provision "file", source: "cfg/prometheus.yml", destination: "/tmp/prometheus.yml"
          box.vm.provision "shell", inline: <<-EOL
            yum install -y docker node_exporter
            mv /tmp/prometheus.yml /home/vagrant/prometheus.yml
            systemctl enable docker --now
            docker run -d -p 9090:9090 -v /home/vagrant/prometheus.yml:/etc/prometheus/prometheus.yml:z prom/prometheus
            docker run -d -p 3000:3000 grafana/grafana
            echo "Done"
          EOL
      end
  end
end
