# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
  :mpkg => {
        :box_name => "centos/7",
        :ip_addr => '172.16.0.100',
        }
    }

Vagrant.configure("2") do |config|

    MACHINES.each do |boxname, boxconfig|
  
        config.vm.define boxname do |box|
  
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s
  
            box.vm.network "private_network", ip: boxconfig[:ip_addr]
  
            box.vm.provider :virtualbox do |vb|
                    vb.customize ["modifyvm", :id, "--memory", "256"]
  
            box.vm.provision "shell", inline: <<-SHELL
                mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
            SHELL
            
            box.vm.provision "file", source: "./files/default.conf", destination: "/tmp/default.conf"
            box.vm.provision "file", source: "./files/nginx.spec", destination: "/tmp/spec"
            box.vm.provision "file", source: "./files/test.repo", destination: "/tmp/test.repo"
            box.vm.provision "shell", path: "./scripts/1_pkg_install.sh"
            box.vm.provision "shell", path: "./scripts/2_rpm_tree_prepare.sh"
            box.vm.provision "shell", path: "./scripts/3_make.sh"
            box.vm.provision "shell", path: "./scripts/4_repo_create.sh"
            end
        end
    end
end
