---
- hosts: centralServer
  become: yes
  tasks:
  - name: "Install EPEL"
    yum:
      name: epel-release
      state: present
  - name: "Install nginx"
    yum:
      name: nginx
      state: present
      update_cache: yes
  - name: "Enable nginx and FW"
    service:
      name: "{{ item }}"
      state: restarted
      enabled: yes
    with_items:
      - nginx
      - firewalld
  - name: "Firewalld port open"
    ansible.posix.firewalld:
      service: http
      permanent: yes
      immediate: yes
      state: enabled
