# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |cfg|
    
  cfg.vm.box = "centos/8"
    
  cfg.vm.provider "virtualbox" do |v|
    v.memory = 256
    v.cpus = 1
  end

  cfg.vm.define "nfss" do |nfss|
    nfss.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "net1"
    nfss.vm.hostname = "nfss"
    nfss.vm.provision "shell", path: "./scripts/nfss_script.sh"
  end

  cfg.vm.define "nfsc" do |nfsc|
    nfsc.vm.network "private_network", ip: "192.168.50.11", virtualbox__intnet: "net1"
    nfsc.vm.hostname = "nfsc"
    nfsc.vm.provision "file", source: "./files/mnt-share.mount", destination: "/tmp/mnt-share.mount"
    nfsc.vm.provision "shell", path: "./scripts/nfsc_script.sh"
  end
    # udp, nfsv3
end
