# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :web => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.150'
  },
  :log => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.160'
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "200"]
          end
          box.vm.provision "shell", inline: <<-EOL
            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
            sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            systemctl restart sshd
          EOL
          
          box.vm.provision "ansible" do |ansible|
              ansible.playbook = "main.yml"
              ansible.become = "true"
              ansible.groups = {
                  "webserver" => ["web"],
                  "logserver" => ["log"]
              }
          end
      end
  end
end
