# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
  :pam => {
        :box_name => "centos/7",
        :ip_addr => '172.16.0.100',
        }
    }

Vagrant.configure("2") do |config|

    MACHINES.each do |boxname, boxconfig|
  
        config.vm.define boxname do |box|
  
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s
  
            box.vm.network "private_network", ip: boxconfig[:ip_addr]
  
            box.vm.provider :virtualbox do |vb|
                    vb.customize ["modifyvm", :id, "--memory", "256"]
            end

            box.vm.provision "shell", inline: <<-SHELL
                mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
            SHELL

            box.vm.provision "file", source: "./files/group.conf", destination: "/tmp/group.conf"
            box.vm.provision "file", source: "./files/access.conf", destination: "/tmp/access.conf"
            box.vm.provision "file", source: "./files/login", destination: "/tmp/login"
            box.vm.provision "file", source: "./files/authconfig", destination: "/tmp/authconfig"
            box.vm.provision "shell", inline: "mv /tmp/group.conf /etc/security/group.conf"
            box.vm.provision "shell", inline: "mv /tmp/access.conf /etc/security/access.conf"
            box.vm.provision "shell", inline: "mv /tmp/login /etc/pam.d/login"
            box.vm.provision "shell", inline: "mv /tmp/authconfig /etc/sysconfig/authconfig"
            box.vm.provision "shell", inline: "useradd admuser; useradd nonadmuser; groupadd admingrp; groupadd canauth; usermod -aG admingrp admuser; usermod -aG admingrp,canauth root; usermod -aG admingrp,canauth vagrant"
            box.vm.provision "shell", inline: "echo \"PaSSwD2021\" | passwd --stdin admuser"
            box.vm.provision "shell", inline: "echo \"PaSSwD2021\" | passwd --stdin nonadmuser"
            box.vm.provision "shell", inline: "sed -i 's/^PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config && systemctl restart sshd.service"
            box.vm.provision "shell", inline: "authconfig --updateall"
        end
    end
end
